# BuildingOS AI Count - 微服务架构 Docker Compose 配置
# 6个独立容器：PostgreSQL、EMQX5.8、Nginx、NestJS后端、Python AI、TDengine、Redis

services:
  # 1. PostgreSQL 数据库服务
  postgres:
    image: postgres:15
    container_name: buildingos-postgres
    environment:
      - POSTGRES_DB=buildingos
      - POSTGRES_USER=buildingos
      - POSTGRES_PASSWORD=buildingos
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - buildingos-network
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # 2. Redis 缓存服务
  redis:
    image: redis:7-alpine
    container_name: buildingos-redis
    command: >
      redis-server
      --appendonly yes
      --requirepass redis123
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - buildingos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

  # 3. EMQX 5.8 MQTT消息队列服务
  emqx:
    image: emqx/emqx:5.8.0
    container_name: buildingos-emqx
    environment:
      - EMQX_NAME=buildingos-emqx
      - EMQX_HOST=0.0.0.0
      - EMQX_NODE__COOKIE=buildingos_emqx_cookie
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=emqx123
      - EMQX_AUTH__USER__1__USERNAME=buildingos
      - EMQX_AUTH__USER__1__PASSWORD=mqtt123
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    ports:
      - "1883:1883"      # MQTT
      - "8083:8083"      # MQTT over WebSocket
      - "8084:8084"      # MQTT over SSL
      - "8883:8883"      # MQTT over SSL
      - "18083:18083"    # Dashboard
    networks:
      - buildingos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "emqx ctl status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # 4. TDengine 时序数据库服务
  tdengine:
    image: tdengine/tdengine:3.3.2.0
    container_name: buildingos-tdengine
    environment:
      - TAOS_FQDN=tdengine
      - TAOS_FIRST_EP=tdengine:6030
      - TAOS_SERVER_PORT=6030
      - TAOS_LOG_DIR=/var/log/taos
      - TAOS_DATA_DIR=/var/lib/taos
      - TAOS_ARBITRATOR=tdengine:6042
    volumes:
      - tdengine_data:/var/lib/taos
      - tdengine_log:/var/log/taos
      - ./explorer.toml:/etc/taos/explorer.toml:ro  # 自定义taosExplorer配置文件
    ports:
      - "6030:6030"      # TDengine 客户端连接端口
      - "6041:6041"      # RESTful 接口端口
      - "6043:6043"      # TDengine 集群通信端口
      - "6044:6044"      # TDengine 数据同步端口
      - "6060:6060"      # taosExplorer Web管理界面端口
    networks:
      - buildingos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "taos -s 'show databases;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # 5. Grafana 数据可视化服务
  grafana:
    image: grafana/grafana:10.2.0
    container_name: buildingos-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana123
      - GF_INSTALL_PLUGINS=tdengine-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=tdengine-datasource
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
    ports:
      - "3000:3000"      # Grafana Web界面端口
    networks:
      - buildingos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    depends_on:
      - tdengine
      - postgres


# 卷定义
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  emqx_data:
    driver: local
  emqx_log:
    driver: local
  upload_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/uploads
  static_data:
    driver: local
  temp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/temp
  stream_cache:
    driver: local
  backend_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/logs
  python_ai_logs:
    driver: local
  python_ai_models:
    driver: local
  tdengine_data:
    driver: local
  tdengine_log:
    driver: local
  grafana_data:
    driver: local
  grafana_logs:
    driver: local


# 网络定义
networks:
  buildingos-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
    driver_opts:
      com.docker.network.bridge.name: buildingos-br0
      com.docker.network.driver.mtu: 1500