apiVersion: v1
kind: Namespace
metadata:
  name: buildingos
  labels:
    name: buildingos
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildingos-config
  namespace: buildingos
data:
  # 数据库配置
  POSTGRES_DB: "buildingos"
  POSTGRES_USER: "buildingos"
  
  # Redis 配置
  REDIS_PORT: "6379"
  
  # TDengine 配置
  TDENGINE_PORT: "6030"
  TDENGINE_HTTP_PORT: "6041"
  
  # 后端应用配置
  NODE_ENV: "production"
  API_PREFIX: "api/v1"
  PORT: "3001"
  
  # 日志配置
  LOG_LEVEL: "info"
  
  # 文件上传配置
  MAX_FILE_SIZE: "10MB"
  UPLOAD_DEST: "/app/uploads"
---
apiVersion: v1
kind: Secret
metadata:
  name: buildingos-secrets
  namespace: buildingos
type: Opaque
stringData:
  # 数据库密码
  POSTGRES_PASSWORD: "buildingos_k8s_2024"
  
  # Redis 密码
  REDIS_PASSWORD: "redis_k8s_2024"
  
  # TDengine 密码
  TDENGINE_PASSWORD: "taos_k8s_2024"
  
  # JWT 密钥
  JWT_SECRET: "BuildingOS_K8s_JWT_Secret_2024"
  
  # MQTT 密码
  MQTT_PASSWORD: "mqtt_k8s_2024"